def dehash(hash)
	if hash == "0d86"
		$data.write "if"
	elsif hash == "226d"
		$data.write "menu"
	elsif hash == "22ff"
		$data.write "mesg"
	elsif hash == "24e1"
		$data.write "radio"
	elsif hash == "306a"
		$data.write "light"
	elsif hash == "430d"
		$data.write "delay"
	elsif hash == "4ad9"
		$data.write "system"
	elsif hash == "5c9e"
		$data.write "varsave"
	elsif hash == "64c0"
		$data.write "eval"
	elsif hash == "698d"
		$data.write "sound"
	elsif hash == "9906"
		$data.write "chara"
	elsif hash == "9a1f"
		$data.write "start"
	elsif hash == "a242"
		$data.write "demo"
	elsif hash == "b96e"
		$data.write "print"
	elsif hash == "c091"
		$data.write "map"
	elsif hash == "c8bb"
		$data.write "load"
	elsif hash == "dbab"
		$data.write "ntrap"
	elsif hash == "e43c"
		$data.write "str_status"
	elsif hash == "ec9d"
		$data.write "jimaku"
	elsif hash == "eee9"
		$data.write "camera"


	elsif hash == "6d43"
		$data.write "00a_o1"
	elsif hash == "6d44"
		$data.write "00a_o2"
	elsif hash == "6d45"
		$data.write "00a_o3"
	elsif hash == "6d46"
		$data.write "00a_o4"
	elsif hash == "6da3"
		$data.write "00a_r1"
	elsif hash == "6da4"
		$data.write "00a_r2"
	elsif hash == "7693"
		$data.write "sne_wet2"
	elsif hash == "c661"
		$data.write "00a"
	elsif hash == "e224"
		$data.write "null"
	elsif hash == "e8fe"
		$data.write "sne_00a"





	elsif hash == "21ca"
		$data.write "Solid_Snake"
	elsif hash == "6588"
		$data.write "Roy_Campbell"
	elsif hash == "9475"
		$data.write "Naomi"
	elsif hash == "95f2"
		$data.write "Meryl"
	elsif hash == "d78a"
		$data.write "Mei_Ling"
	elsif hash == "7982"
		$data.write "Cyborg_Ninja"
	elsif hash == "33af"
		$data.write "Unknown01"
	elsif hash == "6c22"
		$data.write "Master_Miller"
	elsif hash == "3d2c"
		$data.write "Otacon"
	elsif hash == "fb95"
		$data.write "Jim_Houseman"
	elsif hash == "7c90"
		$data.write "Unknown00"
	else
		$data.write "#{hash}"
	end
end